bc_app/urls.py
from django.urls import path
from .views import login_page, admin_page, logout_user, zenotiUsers_page, staff_page, employee_profile_page, edit_user_modal_popup, slr_audit_overview, slr_audit_detail, edit_slr_audit, edit_slr_salon_profile, edit_slr_salon_action_required, edit_slr_salon_extra_data, edit_slr_salon_reviewed_data, edit_slr_salon_status_dropdown, admin_zenotiCenter_page, slr_audit_access, edit_slr_access_popup, admin_team_list_page, edit_admin_modal_popup, central_access_page, edit_central_access_popup, sent_selected_user_list_to_frontend, save_selected_user_responsible, sent_all_user_list_and_compliance_to_frontend, delete_user_response, stafflist_page, kra_list_page, edit_kra_popup_data, admin_center_profile_page
urlpatterns = [
    path('user_login/', login_page, name='user_login'),
    path('user_logout/', logout_user, name='user_logout'),
    path('', admin_page, name='admin_page'),
    path('zenotiCenter_page/', admin_zenotiCenter_page,
         name='zenotiCenter_page'),
    path('body_craft_center_profile/<str:pk>/', admin_center_profile_page,
         name='body_craft_center_profile'),
    path('zenoti_staffs_list/', zenotiUsers_page,
         name='zenoti_staffs_list'),
    path('admin_team_list_page/', admin_team_list_page,
         name='admin_team_list_page'),
    path('edit_admin_modal_popup/', edit_admin_modal_popup,
         name='edit_admin_modal_popup'),
    path('staff_lists/', stafflist_page,
         name='staff_lists'),
    path('edit_user_modal_popup/', edit_user_modal_popup,
         name='edit_user_modal_popup'),
    path('kra_lists/', kra_list_page, name='kra_lists'),
    path('edit_kra_popup_data/', edit_kra_popup_data, name='edit_kra_popup_data'),
    path('body_craft_staff_profile/<str:pk>/', employee_profile_page,
         name='body_craft_staff_profile'),
    path('central_audit_access/', central_access_page,
         name='central_audit_access'),
    path('edit_central_access_popup/', edit_central_access_popup,
         name='edit_central_access_popup'),
    path('slr_audit_access/', slr_audit_access, name='slr_audit_access'),
    path('slr_salon/', slr_audit_overview, name='slr_salon'),
    path('slr_salon/<str:pk>/',
         slr_audit_detail, name='slr_salon_profile'),
    path('edit_slr_access_popup/', edit_slr_access_popup,
         name='edit_slr_access_popup'),
    path('edit_slr_salon_audit/', edit_slr_audit, name='edit_slr_salon_audit'),
    path('edit_slr_salon_profile/', edit_slr_salon_profile,
         name='edit_slr_salon_profile'),
    path('edit_slr_salon_extra_data/', edit_slr_salon_extra_data,
         name='edit_slr_salon_extra_data'),
    path('edit_slr_salon_action_required/', edit_slr_salon_action_required,
         name='edit_slr_salon_action_required'),
    path('edit_slr_salon_status_dropdown/', edit_slr_salon_status_dropdown,
         name='edit_slr_salon_status_dropdown'),
    path('edit_slr_salon_reviewed_data/', edit_slr_salon_reviewed_data,
         name='edit_slr_salon_reviewed_data'),
    path('sent_selected_user_list_to_frontend/', sent_selected_user_list_to_frontend,
         name='sent_selected_user_list_to_frontend'),
    path('save_selected_user_responsible/', save_selected_user_responsible,
         name='save_selected_user_responsible'),
    path('sent_all_user_list_and_compliance_to_frontend/', sent_all_user_list_and_compliance_to_frontend,
         name='sent_all_user_list_and_compliance_to_frontend'),
    path('delete_user_response/', delete_user_response,
         name='delete_user_response'),
]

bc_new_testing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bc_app.urls')),
    path('', include('mystery_shopping.urls')),
    path('', include('roster.urls')),
]

bc_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserTypes(models.Model):
    user_type = models.CharField(max_length=100)
    # unique_id = models.CharField(max_length=10)

    def __str__(self):
        return str(self.user_type)


class AuditTypes(models.Model):
    audit_type = models.CharField(max_length=100)

    def __str__(self):
        return str(self.audit_type)


class WeekOffOptions(models.Model):
    option = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.option)


class KRACategory(models.Model):
    category = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.category)


class KRADesignation(models.Model):
    category = models.ForeignKey(
        KRACategory, null=True, blank=True, on_delete=models.CASCADE
    )
    designation = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.designation)


class KRA(models.Model):
    kra = models.CharField(max_length=100, null=True, blank=True)
    designation = models.ForeignKey(
        KRADesignation, null=True, blank=True, on_delete=models.CASCADE
    )
    start_time = models.TimeField(max_length=100, null=True, blank=True)
    end_time = models.TimeField(max_length=100, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.kra)


class Location(models.Model):
    location = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.location)

# this center data is what we are getting from zenoti


class ZenotiCentersData(models.Model):
    zenoticenterId = models.CharField(max_length=100, null=True, blank=True)
    code = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    display_name = models.CharField(max_length=100, null=True, blank=True)
    address_1 = models.CharField(max_length=500, null=True, blank=True)
    address_2 = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.name) + '-' + str(self.code)


class ExtendedZenotiCenterData(models.Model):
    CENTRESTATUS = (
        ('Active', 'Active'),
        ('InActive', 'InActive')
    )
    zenoti_data = models.OneToOneField(
        ZenotiCentersData, null=True, blank=True, on_delete=models.CASCADE
    )
    opening_time = models.TimeField(max_length=100, null=True, blank=True)
    closing_time = models.TimeField(max_length=100, null=True, blank=True)
    closed_on = models.ManyToManyField(WeekOffOptions, blank=True)
    center_status = models.CharField(
        max_length=200, null=True, blank=True, default='Active', choices=CENTRESTATUS)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.zenoti_data.name)


class CenterKra(models.Model):
    center = models.ForeignKey(
        ExtendedZenotiCenterData, null=True, blank=True, on_delete=models.CASCADE
    )
    kra = models.ForeignKey(KRA, blank=True, null=True,
                            on_delete=models.SET_NULL)
    location = models.ForeignKey(
        Location, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.kra)


class UserProfile(models.Model):
    ENTRANCE_TYPE = (
        ('Zenoti', 'Zenoti'),
        ('Non Zenoti', 'Non Zenoti')
    )
    USERSTATUS = (
        ('Active', 'Active'),
        ('InActive', 'InActive')
    )
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE
    )
    is_super_admin = models.BooleanField(default=False, null=True, blank=True)
    is_audit_admin = models.BooleanField(default=False, null=True, blank=True)
    profile_pic = models.ImageField(
        default="profile1.jpg", null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    user_type = models.CharField(
        max_length=100, blank=True, choices=ENTRANCE_TYPE)
    user_type_name = models.ManyToManyField(UserTypes, blank=True)
    user_status = models.CharField(
        max_length=200, null=True, blank=True, choices=USERSTATUS)
    roster_access = models.BooleanField(default=False, null=True, blank=True)
    associated_center = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True)
    associated_kra = models.ManyToManyField(
        KRA, blank=True)
    primary_kra = models.ForeignKey(
        KRA, related_name='primary_kra', blank=True, null=True, on_delete=models.SET_NULL)
    associated_location = models.ManyToManyField(
        Location, blank=True)
    office_start_time = models.TimeField(max_length=100, null=True, blank=True)
    office_end_time = models.TimeField(max_length=100, null=True, blank=True)
    week_off = models.ManyToManyField(WeekOffOptions, blank=True)
    is_manager = models.BooleanField(default=False, null=True, blank=True)
    date_of_joining = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class SecretKeyModel(models.Model):
    token = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return str(self.token)

# this employee data is what we are getting from zenoti


class ZenotiEmployeesData(models.Model):
    user = models.ForeignKey(
        UserProfile, null=True, blank=True, on_delete=models.CASCADE
    )
    # zenoticenterId = models.CharField(max_length=100, null=True, blank=True)
    employee_code = models.CharField(max_length=100, null=True, blank=True)
    employee_id = models.CharField(max_length=100, null=True, blank=True)
    employee_name = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=500, null=True, blank=True)
    job_info = models.CharField(max_length=500, null=True, blank=True)
    zenoti_center = models.ManyToManyField(
        ZenotiCentersData, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class AssociatedRoleOptions(models.Model):
    option = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.option)


class ExtendedZenotiEmployeesData(models.Model):
    zenoti_data = models.ForeignKey(
        ZenotiEmployeesData, null=True, blank=True, on_delete=models.CASCADE
    )
    associated_center = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True)
    associated_kra = models.ManyToManyField(
        KRA, blank=True)
    office_start_time = models.TimeField(max_length=100, null=True, blank=True)
    office_end_time = models.TimeField(max_length=100, null=True, blank=True)
    week_off = models.ManyToManyField(WeekOffOptions, blank=True)
    is_manager = models.BooleanField(default=False, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.zenoti_data.user)


class EmployeesLeaveData(models.Model):
    LEAVESTATUS = (
        ('Approved', 'Approved'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected'),
    )
    user_profile = models.ForeignKey(
        UserProfile, null=True, blank=True, on_delete=models.CASCADE
    )
    leave_from_date = models.DateField(null=True, blank=True)
    leave_to_date = models.DateField(null=True, blank=True)
    note = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(
        max_length=200, null=True, blank=True, choices=LEAVESTATUS)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user_profile.user)


class MonthAudit(models.Model):
    month = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.month)


class CentralAccess(models.Model):
    staff = models.ManyToManyField(
        UserProfile, blank=True)
    audit = models.ManyToManyField(AuditTypes, blank=True)
    auditor = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='auditor_of'
    )
    project_owner = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='project_manager_of'
    )
    audit_reviewer = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='audit_reviewer_of'
    )
    senior_management = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='senior_management_of'
    )

    def __str__(self):
        return str(self.staff) + ' - ' + str(self.audit)


class AuditAccess(models.Model):
    AUDIT_TYPE = (
        ('SLR Salon', 'SLR Salon'),
    )
    audit = models.CharField(max_length=200, null=True,
                             blank=True, choices=AUDIT_TYPE)
    center = models.ForeignKey(
        ExtendedZenotiCenterData, null=True, blank=True, on_delete=models.CASCADE
    )
    user_type_name = models.ForeignKey(
        UserTypes, blank=True, on_delete=models.CASCADE)
    edit_access = models.ManyToManyField(UserProfile, blank=True)
    view_access = models.ManyToManyField(

templates/employee_profile_tabs/extradata_tab.html
{% load static %}
<div class="p-4" id="extra_data_div">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-md-2"> <strong>First Name</strong>
                        <br>
                        <input class="form-control" type="text" name="first_name" value="{{employee_detail.user.first_name|default_if_none:''}}">
                    </div>
                    <div class="col-md-3"> <strong>Last Name</strong>
                        <br>
                        <input class="form-control" type="text" name="last_name" value="{{employee_detail.user.last_name|default_if_none:''}}">
                    </div>
                    <div class="col-md-3"> <strong>Associated Centers</strong>
                        <br>
                        {{form.associated_center}}
                    </div>
                    <div class="col-md-2"> <strong>Associated KRAs</strong>
                        <br>
                        {{form.associated_kra}}
                    </div>
                    <div class="col-md-2"> <strong>Associated Location</strong>
                        <br>
                        {{form.associated_location}}
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-md-2"> <strong>Primary KRA</strong>
                        <br>
                        {{form.primary_kra}}
                    </div>
                    <div class="col-md-4"> <strong>Office Time</strong>
                        <br>
                        <div class="row">
                            <div class="col">
                                {{form.office_start_time}}
                            </div>
                            <div class="col">
                                {{form.office_end_time}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"> <strong>Week Off</strong>
                        <br>
                        {{form.week_off}}
                    </div>
                    <div class="col-md-2"> <strong>Status</strong>
                        <br>
                        {{form.user_status}}
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col text-center">
                <div class="form-check">
                    <br>
                    <!-- <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required> -->
                    {{form.roster_access}}
                    <label class="form-check-label" for="invalidCheck">
                        <strong>Get Roster Access ?</strong>
                    </label>
                </div>
            </div>
            <div class="col text-center">
                <div class="form-check">
                    <br>
                    <!-- <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required> -->
                    {{form.is_manager}}
                    <label class="form-check-label" for="invalidCheck">
                        <strong>The Staff is Manager ?</strong>
                    </label>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-2">
            <button class="btn btn-success" type="submit" name="extra_data_form">
                Update
            </button>
        </div>
    </form>
    <div>
        <Button class="btn btn-info text-white" data-toggle="modal" data-target="#remove_center_modal">Remove Center and delete Rosters</Button>
    </div>
</div>


<!-- remove center modal  -->
<div class="modal fade" id="remove_center_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-info" id="exampleModalLabel">Select center to remove</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <select class="form-control" name="remove_centers" id="remove_centers" required>
                        <option value="">Select center to remove</option>
                        {% for center in employee_detail.associated_center.all %}
                        <option value="{{center.id}}">{{center}}</option>
                        {% endfor %}
                    </select>
                    <div class="row justify-content-center">
                        <button class="btn btn-danger mt-2" name="remove_center" type="submit">Remove</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
            $('#id_associated_center').select2({
                dropdownAutoWidth: true,
                multiple: true,
                width: '100%',
                height: '30px',
                placeholder: "Select",
                allowClear: true,
                // dropdownParent: $('#extra_data_div')
            });

            $('#id_week_off').select2({
                dropdownAutoWidth: true,
                multiple: true,
                width: '100%',
                height: '30px',
                placeholder: "Select",
                allowClear: true,
                // dropdownParent: $('#extra_data_div')
            });

            $('#id_associated_role').select2({
                dropdownAutoWidth: true,
                multiple: true,
                width: '100%',
                height: '30px',
                placeholder: "Select",
                allowClear: true,
                // dropdownParent: $('#extra_data_div')
            });

            $('#id_associated_location').select2({
            dropdownAutoWidth: true,
            multiple: true,
            width: '100%',
            height: '30px',
            placeholder: "Select",
            allowClear: true,
            // dropdownParent: $('#extra_data_div')
        });
            toggleRosterField();

        });

        function pass_required(t){
            // console.log('val', checkbox_val)
            if (document.getElementById(t.id).checked) {
                // document.getElementById('id_password').required = true;
                document.getElementById('id_roster_access').checked = false;
                document.getElementById('id_roster_access').disabled = true;
            }else{
                // document.getElementById('id_password').required = false;
                document.getElementById('id_roster_access').disabled = false;
            }
        }

        function toggleRosterField() {
            var isManagerCheckbox = document.getElementById('id_is_manager');
            var isRosterCheckbox = document.getElementById('id_roster_access');
            if (isManagerCheckbox.checked) {
                console.log('yes')
                isRosterCheckbox.disabled = true;
            } else {
                isManagerCheckbox.disabled = false;
            }
        }

    
    // var all_maktab = "{{json_allmaktab}}"
    // var json_maktabs = JSON.parse(all_maktab.replace(/&quot;/g, '"'));
    // //     console.log("court id", json_courts)
    // var edit_modal_body_elem = $('#select_center');
    // edit_modal_body_elem.children().remove();
    // var option_elem = ''

    // json_maktabs.forEach(courtObj => {
    //     if (maktab_id_list.includes(courtObj.pk)) {
    //         console.log("yes")
    //         option_elem += `<option selected value="${parseInt(courtObj['pk'])}">${courtObj['fields']['maktab_name']}</option>`;
    //     } else {
    //         option_elem += `<option value="${parseInt(courtObj['pk'])}">${courtObj['fields']['maktab_name']}</option>`;
    //     }
    // });
    // edit_modal_body_elem.append(option_elem);
</script>

templates/employee_profile_tabs/leave_tab.html
{% load static %}
<div class="float-right">
    <button class="btn btn-success text-white" data-toggle="modal" data-target="#add_leave_modal"><i
            class="fas fa-plus"></i> Add Leave</button>
</div>
<div class="p-4" id="leave_data_div">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">From Date</th>
                <th scope="col">To Date</th>
                <th scope="col">Note</th>
                <th scope="col" >Status</th>
            </tr>
        </thead>
        <tbody>
            {% for leave in employee_leave_detail %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{leave.leave_from_date}}</td>
                <td>{{leave.leave_to_date}}</td>
                <td>{{leave.note}}</td>
                <td>{{leave.status}}</td>
                <td><button class=" btn btn-danger" id="edit_{{leave.id}}" data-toggle="modal" 
                    onclick="open_edit_popup('{{leave.leave_from_date}}', '{{leave.leave_to_date}}', '{{leave.id}}')">
                    <i class="fas fa-edit"></i></button></td>
                
                        <!-- edit modal  -->
                <div class="modal fade" id="edit_leave_modal_{{leave.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-info" id="exampleModalLongTitle">Edit Leave
                                </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group mb-4" style="display: none;">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">id</label>
                                        <input type="text" class="form-control" name="edit_leave_id" value="{{leave.id}}" required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">From</label>
                                        <input type="date" class="form-control" name="edit_leave_from" id="edit_leave_from_{{leave.id}}" value="" required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">TO</label>
                                        <input type="date" class="form-control" name="edit_leave_to" id="edit_leave_to_{{leave.id}}" value="" required>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">Note</label>
                                        <input type="text" class="form-control" name="edit_leave_note" value="{{leave.note}}">
                                    </div>
                                    <div class="form-group mb-4">
                                        <label class="mr-sm-2" for="inlineFormCustomSelect">Status</label>
                                        <select class="form-control" name="edit_leave_status" id="" required>
                                            <option {% if leave.status == 'Pending' %} selected {% endif %} value="Pending">Pending</option>
                                            <option {% if leave.status == 'Approved' %} selected {% endif %} value="Approved">Approved</option>
                                            <option {% if leave.status == 'Rejected' %} selected {% endif %} value="Rejected">Rejected</option>
                                        </select>
                                    </div>
                                    <div class="d-flex justify-content-center">
                                        <button class="btn btn-success" type="submit" name="leave_form_edit">Update</button>
                                    </div>
                                </form>
                            </div>
                            <!-- <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            </div> -->
                        </div>
                    </div>
                </div>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- create leave modal -->
<div class="modal fade" id="add_leave_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-info" id="exampleModalLongTitle">Add Leave
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">From</label>
                        <input type="date" class="form-control" name="leave_from" id="" required>
                    </div>
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">TO</label>
                        <input type="date" class="form-control" name="leave_to" id="" required>
                    </div>
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Note</label>
                        <input type="text" class="form-control" name="leave_note" id="" required>
                    </div>
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Status</label>
                        <select class="form-control" name="leave_status" id="">
                            <option value="Pending">Pending</option>
                            <option value="Approved">Approved</option>
                            <option value="Rejected">Rejected</option>
                        </select>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-success" type="submit" name="leave_form">Add</button>
                    </div>
                </form>
            </div>
            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div> -->
        </div>
    </div>
</div>
<script>
    function open_edit_popup(from_d, to_d, id){
        var leave_id = id;
        document.getElementById('edit_leave_from_'+leave_id).value = moment(from_d).format('YYYY-MM-DD');
        document.getElementById('edit_leave_to_'+leave_id).value = moment(to_d).format('YYYY-MM-DD');
        $('#edit_leave_modal_'+leave_id).modal('show');
    }
</script>

templates/employee_profile_tabs/password_tab.html
{% load static %} 
<div class="p-4" id="password_tab_div">
    <form method="post"> 
        {% csrf_token %} 
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-md-6"> <strong>Set Password</strong>
                        <br>
                        <input type="text" class="form-control" name="new_password" value="{{employee_detail.password|default_if_none:''}}">
                        <div class="text-center mt-2">
                            <button class="btn btn-success" type="submit" name="set_staff_password"> Update </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>