bc_app/urls.py
from django.urls import path
from .views import login_page, admin_page, logout_user, zenotiUsers_page, staff_page, employee_profile_page, edit_user_modal_popup, slr_audit_overview, slr_audit_detail, edit_slr_audit, edit_slr_salon_profile, edit_slr_salon_action_required, edit_slr_salon_extra_data, edit_slr_salon_reviewed_data, edit_slr_salon_status_dropdown, admin_zenotiCenter_page, slr_audit_access, edit_slr_access_popup, admin_team_list_page, edit_admin_modal_popup, central_access_page, edit_central_access_popup, sent_selected_user_list_to_frontend, save_selected_user_responsible, sent_all_user_list_and_compliance_to_frontend, delete_user_response, stafflist_page, kra_list_page, edit_kra_popup_data, admin_center_profile_page
urlpatterns = [
    path('user_login/', login_page, name='user_login'),
    path('user_logout/', logout_user, name='user_logout'),
    path('', admin_page, name='admin_page'),
    path('zenotiCenter_page/', admin_zenotiCenter_page,
         name='zenotiCenter_page'),
    path('body_craft_center_profile/<str:pk>/', admin_center_profile_page,
         name='body_craft_center_profile'),
    path('zenoti_staffs_list/', zenotiUsers_page,
         name='zenoti_staffs_list'),
    path('admin_team_list_page/', admin_team_list_page,
         name='admin_team_list_page'),
    path('edit_admin_modal_popup/', edit_admin_modal_popup,
         name='edit_admin_modal_popup'),
    path('staff_lists/', stafflist_page,
         name='staff_lists'),
    path('edit_user_modal_popup/', edit_user_modal_popup,
         name='edit_user_modal_popup'),
    path('kra_lists/', kra_list_page, name='kra_lists'),
    path('edit_kra_popup_data/', edit_kra_popup_data, name='edit_kra_popup_data'),
    path('body_craft_staff_profile/<str:pk>/', employee_profile_page,
         name='body_craft_staff_profile'),
    path('central_audit_access/', central_access_page,
         name='central_audit_access'),
    path('edit_central_access_popup/', edit_central_access_popup,
         name='edit_central_access_popup'),
    path('slr_audit_access/', slr_audit_access, name='slr_audit_access'),
    path('slr_salon/', slr_audit_overview, name='slr_salon'),
    path('slr_salon/<str:pk>/',
         slr_audit_detail, name='slr_salon_profile'),
    path('edit_slr_access_popup/', edit_slr_access_popup,
         name='edit_slr_access_popup'),
    path('edit_slr_salon_audit/', edit_slr_audit, name='edit_slr_salon_audit'),
    path('edit_slr_salon_profile/', edit_slr_salon_profile,
         name='edit_slr_salon_profile'),
    path('edit_slr_salon_extra_data/', edit_slr_salon_extra_data,
         name='edit_slr_salon_extra_data'),
    path('edit_slr_salon_action_required/', edit_slr_salon_action_required,
         name='edit_slr_salon_action_required'),
    path('edit_slr_salon_status_dropdown/', edit_slr_salon_status_dropdown,
         name='edit_slr_salon_status_dropdown'),
    path('edit_slr_salon_reviewed_data/', edit_slr_salon_reviewed_data,
         name='edit_slr_salon_reviewed_data'),
    path('sent_selected_user_list_to_frontend/', sent_selected_user_list_to_frontend,
         name='sent_selected_user_list_to_frontend'),
    path('save_selected_user_responsible/', save_selected_user_responsible,
         name='save_selected_user_responsible'),
    path('sent_all_user_list_and_compliance_to_frontend/', sent_all_user_list_and_compliance_to_frontend,
         name='sent_all_user_list_and_compliance_to_frontend'),
    path('delete_user_response/', delete_user_response,
         name='delete_user_response'),
]

bc_new_testing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bc_app.urls')),
    path('', include('mystery_shopping.urls')),
    path('', include('roster.urls')),
]

bc_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserTypes(models.Model):
    user_type = models.CharField(max_length=100)
    # unique_id = models.CharField(max_length=10)

    def __str__(self):
        return str(self.user_type)


class AuditTypes(models.Model):
    audit_type = models.CharField(max_length=100)

    def __str__(self):
        return str(self.audit_type)


class WeekOffOptions(models.Model):
    option = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.option)


class KRACategory(models.Model):
    category = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.category)


class KRADesignation(models.Model):
    category = models.ForeignKey(
        KRACategory, null=True, blank=True, on_delete=models.CASCADE
    )
    designation = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.designation)


class KRA(models.Model):
    kra = models.CharField(max_length=100, null=True, blank=True)
    designation = models.ForeignKey(
        KRADesignation, null=True, blank=True, on_delete=models.CASCADE
    )
    start_time = models.TimeField(max_length=100, null=True, blank=True)
    end_time = models.TimeField(max_length=100, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.kra)


class Location(models.Model):
    location = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.location)

# this center data is what we are getting from zenoti


class ZenotiCentersData(models.Model):
    zenoticenterId = models.CharField(max_length=100, null=True, blank=True)
    code = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    display_name = models.CharField(max_length=100, null=True, blank=True)
    address_1 = models.CharField(max_length=500, null=True, blank=True)
    address_2 = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.name) + '-' + str(self.code)


class ExtendedZenotiCenterData(models.Model):
    CENTRESTATUS = (
        ('Active', 'Active'),
        ('InActive', 'InActive')
    )
    zenoti_data = models.OneToOneField(
        ZenotiCentersData, null=True, blank=True, on_delete=models.CASCADE
    )
    opening_time = models.TimeField(max_length=100, null=True, blank=True)
    closing_time = models.TimeField(max_length=100, null=True, blank=True)
    closed_on = models.ManyToManyField(WeekOffOptions, blank=True)
    center_status = models.CharField(
        max_length=200, null=True, blank=True, default='Active', choices=CENTRESTATUS)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.zenoti_data.name)


class CenterKra(models.Model):
    center = models.ForeignKey(
        ExtendedZenotiCenterData, null=True, blank=True, on_delete=models.CASCADE
    )
    kra = models.ForeignKey(KRA, blank=True, null=True,
                            on_delete=models.SET_NULL)
    location = models.ForeignKey(
        Location, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.kra)


class UserProfile(models.Model):
    ENTRANCE_TYPE = (
        ('Zenoti', 'Zenoti'),
        ('Non Zenoti', 'Non Zenoti')
    )
    USERSTATUS = (
        ('Active', 'Active'),
        ('InActive', 'InActive')
    )
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE
    )
    is_super_admin = models.BooleanField(default=False, null=True, blank=True)
    is_audit_admin = models.BooleanField(default=False, null=True, blank=True)
    profile_pic = models.ImageField(
        default="profile1.jpg", null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    user_type = models.CharField(
        max_length=100, blank=True, choices=ENTRANCE_TYPE)
    user_type_name = models.ManyToManyField(UserTypes, blank=True)
    user_status = models.CharField(
        max_length=200, null=True, blank=True, choices=USERSTATUS)
    roster_access = models.BooleanField(default=False, null=True, blank=True)
    associated_center = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True)
    associated_kra = models.ManyToManyField(
        KRA, blank=True)
    primary_kra = models.ForeignKey(
        KRA, related_name='primary_kra', blank=True, null=True, on_delete=models.SET_NULL)
    associated_location = models.ManyToManyField(
        Location, blank=True)
    office_start_time = models.TimeField(max_length=100, null=True, blank=True)
    office_end_time = models.TimeField(max_length=100, null=True, blank=True)
    week_off = models.ManyToManyField(WeekOffOptions, blank=True)
    is_manager = models.BooleanField(default=False, null=True, blank=True)
    date_of_joining = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class SecretKeyModel(models.Model):
    token = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return str(self.token)

# this employee data is what we are getting from zenoti


class ZenotiEmployeesData(models.Model):
    user = models.ForeignKey(
        UserProfile, null=True, blank=True, on_delete=models.CASCADE
    )
    # zenoticenterId = models.CharField(max_length=100, null=True, blank=True)
    employee_code = models.CharField(max_length=100, null=True, blank=True)
    employee_id = models.CharField(max_length=100, null=True, blank=True)
    employee_name = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=500, null=True, blank=True)
    job_info = models.CharField(max_length=500, null=True, blank=True)
    zenoti_center = models.ManyToManyField(
        ZenotiCentersData, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class AssociatedRoleOptions(models.Model):
    option = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.option)


class ExtendedZenotiEmployeesData(models.Model):
    zenoti_data = models.ForeignKey(
        ZenotiEmployeesData, null=True, blank=True, on_delete=models.CASCADE
    )
    associated_center = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True)
    associated_kra = models.ManyToManyField(
        KRA, blank=True)
    office_start_time = models.TimeField(max_length=100, null=True, blank=True)
    office_end_time = models.TimeField(max_length=100, null=True, blank=True)
    week_off = models.ManyToManyField(WeekOffOptions, blank=True)
    is_manager = models.BooleanField(default=False, null=True, blank=True)
    password = models.CharField(max_length=200, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.zenoti_data.user)


class EmployeesLeaveData(models.Model):
    LEAVESTATUS = (
        ('Approved', 'Approved'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected'),
    )
    user_profile = models.ForeignKey(
        UserProfile, null=True, blank=True, on_delete=models.CASCADE
    )
    leave_from_date = models.DateField(null=True, blank=True)
    leave_to_date = models.DateField(null=True, blank=True)
    note = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(
        max_length=200, null=True, blank=True, choices=LEAVESTATUS)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.user_profile.user)


class MonthAudit(models.Model):
    month = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.month)


class CentralAccess(models.Model):
    staff = models.ManyToManyField(
        UserProfile, blank=True)
    audit = models.ManyToManyField(AuditTypes, blank=True)
    auditor = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='auditor_of'
    )
    project_owner = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='project_manager_of'
    )
    audit_reviewer = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='audit_reviewer_of'
    )
    senior_management = models.ManyToManyField(
        ExtendedZenotiCenterData, blank=True, related_name='senior_management_of'
    )

    def __str__(self):
        return str(self.staff) + ' - ' + str(self.audit)


class AuditAccess(models.Model):
    AUDIT_TYPE = (
        ('SLR Salon', 'SLR Salon'),
    )
    audit = models.CharField(max_length=200, null=True,
                             blank=True, choices=AUDIT_TYPE)
    center = models.ForeignKey(
        ExtendedZenotiCenterData, null=True, blank=True, on_delete=models.CASCADE
    )
    user_type_name = models.ForeignKey(
        UserTypes, blank=True, on_delete=models.CASCADE)
    edit_access = models.ManyToManyField(UserProfile, blank=True)
    view_access = models.ManyToManyField(

templates/center_profile_tabs/employee_list_tab.html
{% load static %} 
<div class="p-4" id="">
    <div class="col-md-12">
        <div class="card">
            <div class="table-responsive">
                <table class="table no-wrap user-table mb-0">
                    <thead>
                        <tr>
                            <th scope="col" class="border-0 text-uppercase font-medium pl-4"> Name </th>
                            <th scope="col" class="border-0 text-uppercase font-medium"> KRA </th>
                            <th scope="col" class="border-0 text-uppercase font-medium"> Office Time </th>
                            <th scope="col" class="border-0 text-uppercase font-medium"> Week Off </th>
                        </tr>
                    </thead>
                    <tbody> 
                        {% for user in extended_employee_data %} 
                        <tr>
                            <td class="pl-4">
                                <div class="d-flex align-items-start">
                                    <img src="{% static 'images/unisex.jpg' %}" class="rounded-circle" width="30">
                                    <div class="ml-2">
                                        <h5 class="font-weight-medium mb-0">
                                            <a href="{% url 'body_craft_staff_profile' user.zenoti_data.id %}">
                                                {{user.zenoti_data.employee_name|default_if_none:'' }}
                                            </a>
                                            
                                        </h5>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="text-muted">
                                    {% for kra in user.associated_role.all %}
                                        {{kra.name}} {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </span>
                            </td>
                            <td>
                                <span class="text-muted">
                                    {{user.office_start_time|default_if_none:'' }} - {{user.office_end_time|default_if_none:'' }}
                                </span>
                            </td>
                            <td>
                                <span class="text-muted">
                                    {% for week in user.week_off.all %} {{week.option}} {% if not forloop.last %}, {% endif %} {% endfor %}
                                </span>
                            </td>
                        </tr> 
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

templates/center_profile_tabs/extended_data_tab.html
{% load static %}
<div class="p-4" id="extra_data_div">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-md-3"> <strong>Opening Time</strong>
                        <br>
                        {{form.opening_time}}
                    </div>
                    <div class="col-md-3"> <strong>Closing Time</strong>
                        <br>
                        {{form.closing_time}}
                    </div>
                    <div class="col-md-3"> <strong>Closed on</strong>
                        <br>
                        {{form.closed_on}}
                    </div>
                    <div class="col-md-3">
                        <br>
                        {{form.center_status}}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-2">
            <button class="btn btn-success" type="submit" name="extra_data_form">
                Update
            </button>
        </div>
    </form>
</div>


<script>
    $(document).ready(function () {
            $('#id_closed_on').select2({
                dropdownAutoWidth: true,
                multiple: true,
                width: '100%',
                height: '30px',
                placeholder: "Select",
                allowClear: true,
                // dropdownParent: $('#extra_data_div')
            });
        });

    $(document).ready(function () {
            $('#id_position').select2({
                dropdownAutoWidth: true,
                multiple: true,
                width: '100%',
                height: '30px',
                placeholder: "Select",
                allowClear: true,
                // dropdownParent: $('#extra_data_div')
            });
        });
</script>

templates/center_profile_tabs/kra_list_tab.html
{% load static %}
<div class="row p-4">
    <div class="col-6">
        <table class="table">
            <thead>
                <th>KRA</th>
                <th>Location</th>
            </thead>
            <tbody>
                {% for each_kra in all_kra_with_location_of_this_center %}
                <tr>
                    <td>
                        {{each_kra.kra}}
                    </td>
                    <td>
                        {{each_kra.location.location}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Select KRA</label>
                        <select class="form-control" name="selected_kra" id="">
                            <option value=""></option>
                            {% for each_kra in all_kra_list %}
                            <option value="{{each_kra.id}}">{{each_kra.kra}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-4">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Select Location</label>
                        <select class="form-control" name="selected_location" id="">
                            <option value=""></option>
                            {% for each_location in all_location_list %}
                            <option value="{{each_location.id}}">{{each_location.location}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <div class="mt-2"><br>
                        <button class="btn btn-success" name="add_kra_in_center_profile" type="submit">Add</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

templates/center_profile_tabs/zenotidata_tab.html
{% load static %}
<div class="p-4">
    <div>
        <h2><span class="badge badge-secondary">{{center_detail.display_name}}'s data from Zenoti</span></h2>
        <br>
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Center Id</strong>
                        <br>
                        <p class="text-muted">{{center_detail.zenoticenterId}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Center Name</strong>
                        <br>
                        <p class="text-muted">{{center_detail.name}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Display Name</strong>
                        <br>
                        <p class="text-muted">{{center_detail.display_name}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Code</strong>
                        <br>
                        <p class="text-muted">{{center_detail.code}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Address 1</strong>
                        <br>
                        <p class="text-muted">{{center_detail.address_1}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Address 2</strong>
                        <br>
                        <p class="text-muted">{{center_detail.address_2}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>City</strong>
                        <br>
                        <p class="text-muted">{{center_detail.city}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Zip Code</strong>
                        <br>
                        <p class="text-muted">{{center_detail.zip_code}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>State</strong>
                        <br>
                        <p class="text-muted">{{center_detail.state}}</p>
                    </div>
                    <div class="col-md-6 col-xs-6 b-r"> <strong>Country</strong>
                        <br>
                        <p class="text-muted">{{center_detail.country}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>